inputs:
  working-directory:
    description: 'working directory to create build'
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: Run application
      shell: bash
      run: dotnet run --project azure_functions_app1.csproj
      working-directory: ${{ inputs.working-directory }}
