name: Super Linter action
description: Super Linter action for Azure functions dotnet application
    
runs:
  using: "composite"

  steps:
    - name: Super Linter Code base run
      uses: super-linter/super-linter@v4
      env:
          # GITHUB_TOKEN: ${{ inputs.token }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_DOTNET: true
