name: Super Linter action
description: Super Linter action for Azure functions dotnet application
inputs:
  working-directory:
    description: 'working directory to lint'
    required: true
    #type: string
  token:
    description: 'A Github token'
    required: true

    
runs:
  using: "composite"

  steps:
    - id: lint
      name: Super Linter Code base run
      uses: github/super-linter@v5
      #uses: super-linter/super-linter@v5    
      #env:
         # GITHUB_TOKEN: ${{ inputs.token }}
         # VALIDATE_ALL_CODEBASE: false
          # VALIDATE_CSHARP: false
          # FILTER_REGEX_INCLUDE: .*src/.*
          # FILTER_REGEX_INCLUDE: "${{ inputs.working-directory }}"
          # FILTER_REGEX_INCLUDE: "./${PWD/$GITHUB_REPO/}/.*"
         # FILTER_REGEX_INCLUDE: ${{ inputs.working-directory }}
          # /.*\\.(cs|js)$'
          # FILTER_REGEX_EXCLUDE: .github/.*
          # FILTER_REGEX_EXCLUDE: '.*\\.github/.*'
               
    - id: echo
      run: echo "$FILTER_REGEX_INCLUDE"
      shell: bash

          

