name: Super Linter action
description: Super Linter action for Azure functions dotnet application
inputs:
  token:
    description: 'A Github token'
    required: true
    
runs:
  using: "composite"

  steps:
    - name: Super Linter Code base run
      uses: super-linter/super-linter@v6.8.0
      env:
          GITHUB_TOKEN: ${{ inputs.token }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CSHARP: true
