inputs:
  token:
    description: 'A Github token'
    required: true
    
runs:
  using: "composite"

  steps:
    - name: Super Linter Code base run
      uses: super-linter/super-linter@v4
      env:
          # GITHUB_TOKEN: ${{ inputs.token }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_DOTNET: true
