
name: Caller WF to Build Docker Image

on:
  workflow_dispatch:

jobs:
  caller-workflow:
      name: Build .Net app
      uses: missAnkita/Reusable-Workflows/.github/workflows/CD.yml@main
      with:
        runs-on: ubuntu-latest
        working-directory: '.'
        artifact-name: 'artifacts'
        aws-region: 'us-west-2'
        container-repository: 'ankita-ecr01'
        image-tag: 'image1'
        deployment-file: 'k8s/deploydotneteks.yml'
      secrets: inherit

    
            
