name: deploy app

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'working directory for App code'
        required: true
        type: string    
      framework:
        description: 'The type of framework or service'
        required: true
        type: string

jobs:
  detect-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy Static web App
        if: ${{ github.event.inputs.framework == 'static-web-app' }}
        run: |
          echo "Project type is Static Web App"
          #uses: missAnkita/Reusable-Workflows/.github/workflows/deploy-static-webapp.yml@main

      - name: Deploy Angular
        if: ${{ github.event.inputs.framework == 'angular' }}
        run: |
          echo "Project type is Angular"
          #uses: missAnkita/Reusable-Workflows/.github/workflows/deploy-angular.yml@main

      - name: Deploy Azure Functions
        if: ${{ github.event.inputs.framework == 'azure-functions' }}
        run: |
         echo "Project type is Azure Functions"
         uses: missAnkita/Reusable-Workflows/.github/workflows/reusable-dotnet.yml@feature/test-multilingual
         #uses: missAnkita/Reusable-Workflows/.github/workflows/deploy-azure-functions.yml@main
        
      - name: Handle Unknown Framework
        if: ${{ github.event.inputs.framework != 'angular' && github.event.inputs.framework != 'static-web-app' && github.event.inputs.framework != 'azure-functions' }}
        run: |
          echo "Unknown framework: ${{ github.event.inputs.framework }}"
          exit 1
  
