
name: RU WF for linting Azure Functions .NET App

on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
      
      working-directory:
        description: The folder containing the project to build
        type: string
        default: .
        
      run-tests:
        description: Run tests
        type: boolean
        default: true
    
jobs:
  lint:
    name: Lint dotnet app
    
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List Files
        run: ls -R ${{ inputs.working-directory }}

      - name: prin files
        run: ls ${{GITHUB.WORKSPACE}}

      - name: Super Linter Code Base
        uses: missAnkita/Reusable-Workflows/.github/actions/Super-Linter@main
        #with:
          #token: ${{ secrets.GITHUB_TOKEN }}
         # working-directory: ${{ inputs.working-directory }}
        env:
       #   VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_INCLUDE: '.*\.(cs|js|sh)$'
         #'${{ DEFAULT_WORKSPACE }}/.*\\.(cs|js|sh)$'
        
